#!/usr/bin/env bash
# Installs HAProxy version 1.8.
# Enables management.
# Distributes requests.

apt-get update
apt-get install -y haproxy

printf %s "
frontend hbnb-lb_front
        bind *:80
        mode http
        default_backend hbnb-lb_back
backend hbnb-lb_back
        balance roundrobin
        server 1723-web-01 100.26.181.86:80 check
        server 1723-web-02 34.238.192.13:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy start
