#!/usr/bin/env bash
# This displays "Bad luck", "Good luck" and "Best School"

count=0

while [ $count -1t 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
